add fastscnn for segmentation
PaddlePaddle/PaddleX pull request #149
Opened 2020-06-11 03:58 UTC by FlyingQianMM

see title

2020-06-11 09:57 UTC, ZeyuChen requested changes
有一些小的命名问题

2020-06-11 09:57 UTC, ZeyuChen commented on paddlex/cv/models/base.py
>  # copyright (c) 2020 PaddlePaddle Authors. All Rights Reserve.
我发现PaddleX的所有copyright头部都有问题
copyright  -> CopyRight
All rights reseve -> All Rights Reseved.

2020-06-11 09:57 UTC, ZeyuChen commented on paddlex/cv/models/fast_scnn.py
> +class FastSCNN(DeepLabv3p):
FastSCNN 继承自DeepLabv3p?

2020-06-11 09:57 UTC, ZeyuChen commented on paddlex/cv/nets/__init__.py
>  from .mobilenet_v3 import MobileNetV3
为什么不把mobilenetv2,v3都整合到mobilenet一个文件中？

2020-06-12 05:34 UTC, jiangjiajun commented on paddlex/cv/models/fast_scnn.py
> +class FastSCNN(DeepLabv3p):
共用相同的train/eval/predict函数

2020-06-12 05:36 UTC, jiangjiajun commented on paddlex/cv/nets/__init__.py
>  from .mobilenet_v3 import MobileNetV3
结构差异比较大，目前在PaddleClas，PaddleDetection也都是独立的文件，跟他们对齐，便于后面升级

2020-06-12 05:36 UTC, merged