add docs/Paddle-Lite-Demo.md
PaddlePaddle/PaddleX pull request #1914
Opened 2024-08-15 12:30 UTC by zhang-prog

增加端侧部署示例文档

2024-08-15 12:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleX?pullRequest=1914) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleX?pullRequest=1914) before we can accept your contribution.<br/><hr/>**zhangyue66** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleX?pullRequest=1914) it.</sub>

2024-08-19 07:59 UTC, Bobholamovic requested changes
留了一些评论～

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +## 代码介绍、代码讲解、更新模型、更新输入和输出预处理
这个标题有点儿奇怪，建议改成“参考资料”吧

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +# Paddle-Lite-Demo 使用指南
这个文档的定位应该是PaddleX端侧部署demo。可以淡化Paddle-Lite-Demo，它只是一个实现路径，我们的主题应该还是围绕PaddleX。

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +本文主要介绍 Paddle-Lite-Demo 在 Android shell 上的运行方法和如何在更新模型/输入/输出处理下，保证 Paddle-Lite-Demo 仍可继续运行。
这句太长了中间没有标点，稍微拆一下吧，比如把“和如何”换成“，以及如何”。

主题应该是如何将PaddleX导出的模型部署到端侧。可以参考PaddleX其他已有的部署文档。另外，这部分的定位目前是demo。

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +此 Demo 有很好的的易用性和开放性，可在 Demo 中跑自己训练好的模型等。
句子中间出现的单词可以不用首字母大写

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +1. 在本地环境安装好 CMAKE 编译工具，并在 [Android NDK 官网](https://developer.android.google.cn/ndk/downloads)下载当前系统的某个版本的 NDK 软件包。例如，在 Mac 上开发，需要在 Android NDK 官网下载 Mac 平台的 NDK 软件包
`CMAKE`的官方名称应该是`CMake`。此外，除了说明本指南测试过的版本，也需要指明一下理论上支持的版本（只是可能没有全部经过测试）。

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +3. 电脑上安装 adb 工具，用于调试。 adb安装方式如下：
统一一下文档中出现的`adb`和`ADB`的称呼吧。

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +     sudo apt install -y wget adb
是否提供docker镜像？如果不提供，这里可能需要说明，这是debian系的linux发行版的安装方式（redhat、centos常用yum）。

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +    3.3. Window 安装 ADB
Windows

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +## 如何更新预测库
这个步骤是应该在什么时候执行的？

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +### 部署步骤
这一套流程可以适用于所有的任务嘛？是否有不同任务存在区别的地方，需要我们做出说明？

2024-08-19 07:59 UTC, Bobholamovic commented on docs/Paddle-Lite-Demo.md
> +此 Demo 有很好的的易用性和开放性，可在 Demo 中跑自己训练好的模型等。
可能也需要介绍下这份指南适用于哪些任务、哪些模型。

2024-08-19 09:16 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +## 代码介绍、代码讲解、更新模型、更新输入和输出预处理
done

2024-08-19 09:16 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +# Paddle-Lite-Demo 使用指南
done

2024-08-19 09:16 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +本文主要介绍 Paddle-Lite-Demo 在 Android shell 上的运行方法和如何在更新模型/输入/输出处理下，保证 Paddle-Lite-Demo 仍可继续运行。
done

2024-08-19 09:16 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +此 Demo 有很好的的易用性和开放性，可在 Demo 中跑自己训练好的模型等。
done

2024-08-19 09:17 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +1. 在本地环境安装好 CMAKE 编译工具，并在 [Android NDK 官网](https://developer.android.google.cn/ndk/downloads)下载当前系统的某个版本的 NDK 软件包。例如，在 Mac 上开发，需要在 Android NDK 官网下载 Mac 平台的 NDK 软件包
done

2024-08-19 09:18 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +3. 电脑上安装 adb 工具，用于调试。 adb安装方式如下：
done

2024-08-19 09:18 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +    3.3. Window 安装 ADB
done

2024-08-19 09:27 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +     sudo apt install -y wget adb
done，环境易于安装，无docker提供

2024-08-19 09:33 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +### 部署步骤
done，已补上说明

2024-08-19 09:46 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +此 Demo 有很好的的易用性和开放性，可在 Demo 中跑自己训练好的模型等。
done，已补上说明

2024-08-19 09:58 UTC, zhang-prog commented on docs/Paddle-Lite-Demo.md
> +## 如何更新预测库
done，已去除该步骤

2024-08-19 12:08 UTC, Bobholamovic requested changes

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +本文主要介绍 PaddleX 端侧部署 demo 在 Android shell 上的运行方法。
`本文`->`本指南`

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +等 7 个任务的 10 个模型，有很好的的易用性和开放性，可在 demo 中跑自己训练的模型。
这里表述有些太口语化了，可以调整一下

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +- [如何运行 PaddleX 端侧部署 demo](#如何运行-paddlex-端侧部署-demo)
这节建议直接叫“安装流程与使用方式”吧

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +1. 在本地环境安装好 CMake 编译工具，并在 [Android NDK 官网](https://developer.android.google.cn/ndk/downloads)下载当前系统的某个版本的 NDK 软件包。例如，在 Mac 上开发，需要在 Android NDK 官网下载 Mac 平台的 NDK 软件包
“某个版本” -> “符合要求的版本”

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +1. 在本地环境安装好 CMake 编译工具，并在 [Android NDK 官网](https://developer.android.google.cn/ndk/downloads)下载当前系统的某个版本的 NDK 软件包。例如，在 Mac 上开发，需要在 Android NDK 官网下载 Mac 平台的 NDK 软件包
部分自然段遗漏句号，可以检查一下补全。

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +3. 电脑上安装 ADB 工具，用于调试。 ADB 安装方式如下：
标点符号后不用空一格，例如`。 ADB` -> `。ADB`

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +    -  `cmake == 3.20.0`
是不是统一一下风格，前文相似的地方没有加backtick，这里加了

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +    3.2. Linux 安装 ADB
可以统一一下风格，`Mac 电脑安装 ADB：`和`Linux 安装 ADB`在有无“电脑”和有无“：”方面风格不统一

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +此部署步骤适用于下表中提供的 demo：
“此部署步骤适用于下表中提供的 demo” -> “本节描述的部署步骤适用于下表中列举的 demo”

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +此 demo 包含
“此 demo 包含”是否应该修改为“本指南适用于”？

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +运行结果如下所示,并生成一张名叫face_detection.jpg的人脸检测结果图：
`face_detection.jpg`需要用反引号包围

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +2. cd `Paddle-Lite-Demo/libs` 目录，运行 `download.sh` 脚本，下载所需要的 Paddle Lite 预测库，此步骤只需执行一次，即可支持每个 Demo 使用。
“此步骤只需执行一次”之前应该用句号。

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +3. cd `Paddle-Lite-Demo/{Demo Name}/assets` 目录，运行 `download.sh` 脚本，下载 OPT 优化后模型、测试图片和标签文件等
“OPT 优化”是Paddle-Lite官方使用的术语吗？

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +2. cd `Paddle-Lite-Demo/libs` 目录，运行 `download.sh` 脚本，下载所需要的 Paddle Lite 预测库，此步骤只需执行一次，即可支持每个 Demo 使用。
这里建议把“cd”改为“将工作目录切换到”

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +    - 若使用 mac 编译，需要将 `CMakeLists.txt` 中的 `CMAKE_SYSTEM_NAME` 设置为 `darwin`
`使用 mac 编译` -> `在 Mac 系统上编译`

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +此部署步骤适用于下表中提供的 demo：
前面其实已经说过支持的任务了，这里还需要再重复一遍吗？或者这个部分是不是可以提前？

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +```shell
这里应该不是shell，而是text

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +以下为 face_detection 的示例，其他 demo 需按上述步骤改变路径。
具体改变到什么路径呢？是否应该说明？

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +本指南为通用流程，若想要了解更细致的信息，如代码介绍、代码讲解、更新模型、更新输入和输出预处理等，可参考各自部分的详细介绍：
“可参考各自部分的详细介绍” -> “可参考如下文档”

2024-08-19 12:08 UTC, Bobholamovic commented on docs/lite_deploy.md
> +本指南为通用流程，若想要了解更细致的信息，如代码介绍、代码讲解、更新模型、更新输入和输出预处理等，可参考各自部分的详细介绍：
“本指南为通用流程” -> “本指南仅介绍端侧部署 demo 的基本安装、使用流程”

2024-08-19 12:25 UTC, zhang-prog commented on docs/lite_deploy.md
> +本文主要介绍 PaddleX 端侧部署 demo 在 Android shell 上的运行方法。
done

2024-08-19 12:25 UTC, zhang-prog commented on docs/lite_deploy.md
> +- [如何运行 PaddleX 端侧部署 demo](#如何运行-paddlex-端侧部署-demo)
done

2024-08-19 12:25 UTC, zhang-prog commented on docs/lite_deploy.md
> +1. 在本地环境安装好 CMake 编译工具，并在 [Android NDK 官网](https://developer.android.google.cn/ndk/downloads)下载当前系统的某个版本的 NDK 软件包。例如，在 Mac 上开发，需要在 Android NDK 官网下载 Mac 平台的 NDK 软件包
done

2024-08-19 12:25 UTC, zhang-prog commented on docs/lite_deploy.md
> +1. 在本地环境安装好 CMake 编译工具，并在 [Android NDK 官网](https://developer.android.google.cn/ndk/downloads)下载当前系统的某个版本的 NDK 软件包。例如，在 Mac 上开发，需要在 Android NDK 官网下载 Mac 平台的 NDK 软件包
done，已补全，目前所有自然段都有符号结尾。

2024-08-19 12:25 UTC, zhang-prog commented on docs/lite_deploy.md
> +3. 电脑上安装 ADB 工具，用于调试。 ADB 安装方式如下：
done，顺便确认了其他部分

2024-08-19 12:26 UTC, zhang-prog commented on docs/lite_deploy.md
> +    -  `cmake == 3.20.0`
done，应该统一的，上次遗漏了

2024-08-19 12:28 UTC, zhang-prog commented on docs/lite_deploy.md
> +    3.2. Linux 安装 ADB
done，无冒号为统一风格

2024-08-19 12:29 UTC, zhang-prog commented on docs/lite_deploy.md
> +此部署步骤适用于下表中提供的 demo：
done

2024-08-19 12:29 UTC, zhang-prog commented on docs/lite_deploy.md
> +此 demo 包含
done

2024-08-19 12:30 UTC, zhang-prog commented on docs/lite_deploy.md
> +运行结果如下所示,并生成一张名叫face_detection.jpg的人脸检测结果图：
done

2024-08-19 12:31 UTC, zhang-prog commented on docs/lite_deploy.md
> +2. cd `Paddle-Lite-Demo/libs` 目录，运行 `download.sh` 脚本，下载所需要的 Paddle Lite 预测库，此步骤只需执行一次，即可支持每个 Demo 使用。
done

2024-08-19 12:33 UTC, zhang-prog commented on docs/lite_deploy.md
> +3. cd `Paddle-Lite-Demo/{Demo Name}/assets` 目录，运行 `download.sh` 脚本，下载 OPT 优化后模型、测试图片和标签文件等
是的，此术语是从官方readme得来，但改为 `paddle_lite_opt 工具优化后` 是否更好？

2024-08-19 12:34 UTC, zhang-prog commented on docs/lite_deploy.md
> +2. cd `Paddle-Lite-Demo/libs` 目录，运行 `download.sh` 脚本，下载所需要的 Paddle Lite 预测库，此步骤只需执行一次，即可支持每个 Demo 使用。
done

2024-08-19 12:35 UTC, zhang-prog commented on docs/lite_deploy.md
> +    - 若使用 mac 编译，需要将 `CMakeLists.txt` 中的 `CMAKE_SYSTEM_NAME` 设置为 `darwin`
done

2024-08-19 12:36 UTC, zhang-prog commented on docs/lite_deploy.md
> +```shell
done

2024-08-19 12:36 UTC, zhang-prog commented on docs/lite_deploy.md
> +本指南为通用流程，若想要了解更细致的信息，如代码介绍、代码讲解、更新模型、更新输入和输出预处理等，可参考各自部分的详细介绍：
done

2024-08-19 12:37 UTC, zhang-prog commented on docs/lite_deploy.md
> +本指南为通用流程，若想要了解更细致的信息，如代码介绍、代码讲解、更新模型、更新输入和输出预处理等，可参考各自部分的详细介绍：
done

2024-08-19 12:39 UTC, zhang-prog commented on docs/lite_deploy.md
> +以下为 face_detection 的示例，其他 demo 需按上述步骤改变路径。
done

2024-08-19 12:49 UTC, zhang-prog commented on docs/lite_deploy.md
> +此部署步骤适用于下表中提供的 demo：
done

2024-08-19 12:51 UTC, zhang-prog commented on docs/lite_deploy.md
> +等 7 个任务的 10 个模型，有很好的的易用性和开放性，可在 demo 中跑自己训练的模型。
done

2024-08-20 06:40 UTC, Bobholamovic commented on docs/lite_deploy.md
> +本指南适用于下列 7 个任务的 10 个模型，有很好的的易用性和开放性，可在 demo 中使用自己训练的模型。
`有很好的的易用性和开放性，可在 demo 中使用自己训练的模型`这两个子句的主语应该不一样（前者是demo，后者是用户），这样的话可能是一个病句。另外建议这两个子句调整到上一段，这一段只保留“本指南适用于下列xxx”

2024-08-20 06:40 UTC, Bobholamovic commented on docs/lite_deploy.md
> +    - 在运行 `build.sh` 脚本前，需要更改里面 `export NDK_ROOT` 的路径为实际安装的 NDK 路径。
需要更改里面 `export NDK_ROOT` 的路径 -> 需要更改 `NDK_ROOT` 指定的路径

2024-08-20 06:40 UTC, Bobholamovic commented on docs/lite_deploy.md
> + # 2. 下载 OPT 优化后模型、测试图片、标签文件
“OPT”改成“opt 工具”吧

2024-08-20 06:40 UTC, Bobholamovic commented on docs/lite_deploy.md
> + # 1. 下载所需要的 Paddle Lite 预测库
去掉“所”

2024-08-20 06:43 UTC, zhang-prog commented on docs/lite_deploy.md
> +    - 在运行 `build.sh` 脚本前，需要更改里面 `export NDK_ROOT` 的路径为实际安装的 NDK 路径。
done

2024-08-20 06:43 UTC, zhang-prog commented on docs/lite_deploy.md
> + # 2. 下载 OPT 优化后模型、测试图片、标签文件
done

2024-08-20 06:44 UTC, zhang-prog commented on docs/lite_deploy.md
> + # 1. 下载所需要的 Paddle Lite 预测库
done

2024-08-20 06:52 UTC, zhang-prog commented on docs/lite_deploy.md
> +本指南适用于下列 7 个任务的 10 个模型，有很好的的易用性和开放性，可在 demo 中使用自己训练的模型。
done，移动位置时也调整了两个子句的描述

2024-08-20 07:28 UTC, Bobholamovic approved these changes

2024-08-21 15:23 UTC, zhang-prog commented
提错分支，已更改到：https://github.com/PaddlePaddle/PaddleX/pull/1935

2024-08-21 15:24 UTC, closed without merging