add multichannel RemoteSensing
PaddlePaddle/PaddleX pull request #283
Opened 2020-08-21 08:09 UTC by FlyingQianMM

see title

2020-08-21 08:43 UTC, ZeyuChen requested changes
change package name

2020-08-21 08:43 UTC, ZeyuChen commented on paddlex/RemoteSensing/train_demo.py
> +import paddlex.RemoteSensing.transforms as custom_transforms
package name should use lowercase

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/datasets/seg_dataset.py
> +                if line.count(" ") > 1:
这里为什么要加这个判断

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/datasets/seg_dataset.py
>                  items = line.strip().split()
应该是在这里判断len(items) > 2

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/models/deeplabv3p.py
> +                 input_channel=3,
这个参数加到最后面吧，要不然可能会影响之前人写的代码

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/models/fast_scnn.py
> +                 input_channel=3,
同上

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/models/hrnet.py
> +                 input_channel=3,
同上

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/models/unet.py
> +                 input_channel=3,
同上

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/nets/segmentation/deeplabv3p.py
> +                 input_channel=3,
同上

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/nets/segmentation/fast_scnn.py
> +                 input_channel=3,
同上

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/nets/segmentation/hrnet.py
> +                 input_channel=3,
同上

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/nets/segmentation/hrnet.py
> +                 input_channel=3,
原来这个是cv/nets里的，那这里不用改，因为外部用户使用不到这里的接口

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/nets/segmentation/deeplabv3p.py
> +                 input_channel=3,
这里也不用改，忽略『同上』，因为是在cv/nets里面，外部用户使用不到这里的接口

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/nets/segmentation/fast_scnn.py
> +                 input_channel=3,
这里也不用改，忽略『同上』，因为是在cv/nets里面，外部用户使用不到这里的接口

2020-09-01 02:51 UTC, jiangjiajun commented on paddlex/cv/transforms/seg_transforms.py
> +            import gdal
这里如果import不进来，给出提示文档的链接

2020-09-01 06:36 UTC, FlyingQianMM commented on paddlex/cv/datasets/seg_dataset.py
>                  items = line.strip().split()
已修改，感谢～

2020-09-01 06:36 UTC, FlyingQianMM commented on paddlex/cv/models/deeplabv3p.py
> +                 input_channel=3,
已修改，感谢～

2020-09-01 06:36 UTC, FlyingQianMM commented on paddlex/cv/models/fast_scnn.py
> +                 input_channel=3,
已修改，感谢～

2020-09-01 06:36 UTC, FlyingQianMM commented on paddlex/cv/models/hrnet.py
> +                 input_channel=3,
已修改，感谢～

2020-09-01 06:37 UTC, FlyingQianMM commented on paddlex/cv/models/unet.py
> +                 input_channel=3,
已修改，感谢～

2020-09-01 06:37 UTC, FlyingQianMM commented on paddlex/cv/transforms/seg_transforms.py
> +            import gdal
已修改，感谢～

2020-09-01 07:02 UTC, merged