support quality testing case
PaddlePaddle/PaddleX pull request #400
Opened 2020-11-12 14:31 UTC by FlyingQianMM

添加工业质检案例所需模块：
* voc数据集添加generate_image接口，支持泊松融合生成新的图片，并保存真值文件
* faster rcnn:
  ** 支持dcn， backbone添加resnet50_ssld
  ** rcnn阶段支持LibraAssign；支持SoftNMS，CiouNMS；支持设置rcnn输入通道fpn_num_channels；开放rpn_batch_size_per_im 、rpn_fg_fraction 、test_pre_nms_top_n、test_post_nms_top_n参数设置
  ** 支持多通道输入
  ** rpn阶段支持SigmoidFocalLoss，
  ** 支持剪裁
* det_transform支持多通道预处理与数据增强
* pdx.det增加coco_error_analysis接口分析验证集结果

2020-11-13 03:34 UTC, jiangjiajun requested changes

2020-11-13 03:34 UTC, jiangjiajun commented on paddlex/cv/datasets/voc.py
> +
先只支持VOC， 离线处理， paddlex.det.xxxx。

2020-11-13 03:34 UTC, jiangjiajun commented on paddlex/cv/models/base.py
> +            input_channel = self.input_channel
input_channel = getattr(self, 'input_channel', 3)

2020-11-23 08:39 UTC, liuw20 commented on paddlex/cv/models/base.py
> +            input_channel = self.input_channel
what??

2020-11-30 06:45 UTC, jiangjiajun requested changes

2020-11-30 06:45 UTC, jiangjiajun commented on deploy/cpp/src/transforms.cpp
> +    *im = padded_im;
拆成子函数, general_padding, multichannel_padding

2020-11-30 06:45 UTC, jiangjiajun commented on deploy/openvino/src/transforms.cpp
> +  if (im->channels() < 5) {
同上

2020-11-30 06:45 UTC, jiangjiajun commented on docs/examples/industrial_quality_inspection/dataset.md
> +| 1 | 擦花（擦伤）| 表面处理（喷涂）后有轻微擦到其它的东西，造成痕迹 | ![图片](https://agroup-bos-bj.cdn.bcebos.com/bj-be236181808cd68e3ad941efdc16f11d4a04dd35) | 128 |
agroup链接替换为github上链接

2020-11-30 06:45 UTC, jiangjiajun commented on docs/examples/industrial_quality_inspection/README.md
> +本案例面向工业质检场景里的铝材表面缺陷检测，提供了针对GPU端和CPU端两种部署场景下基于PaddleX的解决方案，希望通过梳理优化模型精度和性能的思路能帮助用户更高效地解决实际质检应用中的问题。
加一个案例总结，总结本案例中做的事情，采取的方法和达到的效果

2020-11-30 06:45 UTC, jiangjiajun commented on examples/industrial_quality_inspection/cal_sensitivities_file.py
> +    pdx.slim.cal_params_sensitivities(
新的接口，代码名改，那对应文档中也需要改

2020-11-30 06:45 UTC, jiangjiajun commented on examples/industrial_quality_inspection/cal_tp_fp.py
> +plt.subplot(1, 2, 1)
写成函数，最好加上函数参数的注释

2020-11-30 06:45 UTC, jiangjiajun commented on examples/industrial_quality_inspection/compare.py
> +with open(file_list, 'r') as fr:
同上，拆函数，最好加注释

2020-11-30 06:45 UTC, jiangjiajun commented on examples/industrial_quality_inspection/predict.py
> +det_vis = pdx.det.visualize(
返回值不需要

2020-11-30 06:45 UTC, jiangjiajun commented on examples/industrial_quality_inspection/train_rcnn.py
> +os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3,4'
改成单卡训，对应学习率，warmup等也得要修改

2020-11-30 06:45 UTC, jiangjiajun commented on examples/industrial_quality_inspection/train_yolov3.py
> +os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3,4,5,6,7'
单卡

2020-11-30 06:45 UTC, jiangjiajun commented on paddlex/cv/datasets/voc.py
> +                        cname = 'lou_di'
硬编码？

2020-11-30 06:45 UTC, jiangjiajun commented on paddlex/cv/models/ppyolo.py
> +            batch_size=getattr(self, 'batch_size_per_gpu', 8),
改成直接获取

2020-11-30 06:45 UTC, jiangjiajun commented on paddlex/cv/models/utils/detection_eval.py
> +def makeplot(rs, ps, outDir, class_name, iou_type):
加点注释

2020-12-01 13:00 UTC, FlyingQianMM commented on paddlex/cv/datasets/voc.py
> +
已修改。感谢～

2020-12-01 13:00 UTC, FlyingQianMM commented on paddlex/cv/models/base.py
> +            input_channel = self.input_channel
已修改。感谢～

2020-12-01 13:00 UTC, FlyingQianMM commented on deploy/cpp/src/transforms.cpp
> +    *im = padded_im;
已修改。感谢～

2020-12-01 13:00 UTC, FlyingQianMM commented on deploy/openvino/src/transforms.cpp
> +  if (im->channels() < 5) {
已修改。感谢～

2020-12-01 13:00 UTC, FlyingQianMM commented on docs/examples/industrial_quality_inspection/dataset.md
> +| 1 | 擦花（擦伤）| 表面处理（喷涂）后有轻微擦到其它的东西，造成痕迹 | ![图片](https://agroup-bos-bj.cdn.bcebos.com/bj-be236181808cd68e3ad941efdc16f11d4a04dd35) | 128 |
已修改。感谢～

2020-12-01 13:00 UTC, FlyingQianMM commented on docs/examples/industrial_quality_inspection/README.md
> +本案例面向工业质检场景里的铝材表面缺陷检测，提供了针对GPU端和CPU端两种部署场景下基于PaddleX的解决方案，希望通过梳理优化模型精度和性能的思路能帮助用户更高效地解决实际质检应用中的问题。
已修改。感谢～

2020-12-01 13:01 UTC, FlyingQianMM commented on docs/examples/industrial_quality_inspection/README.md
> +本案例面向工业质检场景里的铝材表面缺陷检测，提供了针对GPU端和CPU端两种部署场景下基于PaddleX的解决方案，希望通过梳理优化模型精度和性能的思路能帮助用户更高效地解决实际质检应用中的问题。
REAME.md里已GPU端和CPU端的方案总结，故开头处没有加上总结。感谢～

2020-12-01 13:01 UTC, FlyingQianMM commented on examples/industrial_quality_inspection/cal_sensitivities_file.py
> +    pdx.slim.cal_params_sensitivities(
已修改。感谢～

2020-12-01 13:01 UTC, FlyingQianMM commented on examples/industrial_quality_inspection/train_rcnn.py
> +os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3,4'
已修改。感谢～

2020-12-01 13:01 UTC, FlyingQianMM commented on examples/industrial_quality_inspection/train_yolov3.py
> +os.environ['CUDA_VISIBLE_DEVICES'] = '0,1,2,3,4,5,6,7'
已修改。感谢～

2020-12-01 13:01 UTC, FlyingQianMM commented on paddlex/cv/datasets/voc.py
> +                        cname = 'lou_di'
已修改。感谢～

2020-12-01 13:02 UTC, FlyingQianMM commented on paddlex/cv/models/ppyolo.py
> +            batch_size=getattr(self, 'batch_size_per_gpu', 8),
已修改为batch_size=getattr(self, 'batch_size_per_gpu', None)。感谢～

2020-12-01 13:02 UTC, FlyingQianMM commented on paddlex/cv/models/utils/detection_eval.py
> +def makeplot(rs, ps, outDir, class_name, iou_type):
已添加注释。感谢～

2020-12-03 02:16 UTC, merged