增加多卡部署
PaddlePaddle/PaddleX pull request #684
Opened 2021-04-22 09:56 UTC by heliqi

1.增加用于多卡部署的文件，multi_gpu_model.h
2.修改demo支持多卡多batch
3.修复det_model中的use_cpu_nms问题 + 删除多余代码

2021-04-22 11:29 UTC, jiangjiajun requested changes

2021-04-22 11:29 UTC, jiangjiajun commented on deploy/cpp/model_deploy/common/include/multi_gpu_model.h
> +  bool Predict(const std::vector<cv::Mat>& imgs, int thread_num = 1,
imgs_start和imgs_end删掉

2021-04-22 11:29 UTC, jiangjiajun commented on deploy/cpp/model_deploy/common/include/multi_gpu_model.h
> +    int model_num = static_cast<int>(gpu_ids.size());
gpu_num

2021-04-22 11:29 UTC, jiangjiajun commented on deploy/cpp/model_deploy/common/include/multi_gpu_model.h
> +  bool Init(const std::string& model_type, const std::string& cfg_file,
这个初始化仍然还是有些疑问，例如这里如果都写了这样，那其它推理方式怎么进行初始化呢

2021-04-23 07:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/PaddlePaddle/PaddleX?pullRequest=684) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/PaddlePaddle/PaddleX?pullRequest=684) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: heliqi<br/>:x: paddle-ci<br/><hr/>**paddle-ci** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/PaddlePaddle/PaddleX?pullRequest=684) it.</sub>

2021-04-25 02:01 UTC, jiangjiajun requested changes

2021-04-25 02:01 UTC, jiangjiajun commented on deploy/cpp/CMakeLists.txt
> +include_directories("${PROJECT_ROOT_DIR}/model_deploy")
这里为什么要加上这句，我记得所有代码的include都是从model_deploy开始写起的

2021-04-25 02:01 UTC, jiangjiajun commented on deploy/cpp/model_deploy/common/include/base_model.h
>      }
这样改的原因是什么呢？

2021-04-25 02:01 UTC, jiangjiajun commented on deploy/cpp/model_deploy/common/include/multi_gpu_model.h
> +    run_id_.clear();
为什么要有run_id_这个成员变量？

2021-04-25 02:19 UTC, heliqi commented on deploy/cpp/CMakeLists.txt
> +include_directories("${PROJECT_ROOT_DIR}/model_deploy")
我之前确认的时候看的demo，没有从model_deploy。 刚看了下除了demo，确实是从model_deploy开始的。我都改下

2021-04-25 02:26 UTC, heliqi commented on deploy/cpp/model_deploy/common/include/base_model.h
>      }
我测试的时候,用之前的代码在多线程进行predict会报错，显示imgs里数据读取错误。 
我当时猜测是imgs.copyTo在拷贝完了后会释放imgs，影响到了主程里的那个imgs，导致别的线程读取时数据不对。

2021-04-25 02:30 UTC, heliqi commented on deploy/cpp/model_deploy/common/include/multi_gpu_model.h
> +    run_id_.clear();
获取结果时，我不知道哪些gpu跑了任务。有可能有GPU分不到数据跑，比如3张卡，只有两张图片

2021-04-25 02:47 UTC, jiangjiajun commented on deploy/cpp/model_deploy/common/include/multi_gpu_model.h
> +    run_id_.clear();
分不到数据时，则传入的vector为空，得到的结果result应该也为空才对

2021-04-25 11:44 UTC, merged