增加linux、windows编译文档
PaddlePaddle/PaddleX pull request #697
Opened 2021-04-28 07:02 UTC by heliqi

1.修复demo下一些格式问题
2.修改deploy/resources/resnet50_imagenet.yml配置文件中没有参数的value为~
3.增加linux、windows编译文档

2021-04-28 07:15 UTC, jiangjiajun requested changes

2021-04-28 07:15 UTC, jiangjiajun commented on deploy/cpp/docs/compile/paddle/linux.md
> +| model_type      | 导出预测模型所用的框架，比如det(PaddleDetection)、seg(PaddleSeg) | 必填               |
这里不是写比如，得列清model_type当前支持哪些

2021-04-28 07:15 UTC, jiangjiajun commented on deploy/cpp/docs/compile/paddle/linux.md
> +| model_filename  | 导出的预测模型 模型(model)的路径,例如`D:/ppyolo/__model__`   | 必填               |
改成model.pdmodel 和model.pdiparams，现在到2.0后不会再有__model__这种命名方式

2021-04-28 07:15 UTC, jiangjiajun commented on deploy/cpp/docs/compile/paddle/linux.md
> +| thread_num      | MKL推理的线程数，默认为1                                     | 默认为 1           |
这里有个疑问，我看代码API中并没提供设置mkl_threadnum的接口，这里文档和代码得一起改

2021-04-28 07:15 UTC, jiangjiajun commented on deploy/cpp/docs/compile/paddle/windows.md
> +**说明**：其中`C++`预测代码在`PaddleX\deploy\cpp` 目录，该目录不依赖任何`PaddleX`下其他目录。所有的公共实现代码在`model_deploy`目录下，而示例demo代码为`demo/model_infer.cpp`。
Linux文档和Windows文档看起来差异很大，不像一个人写的，看得出这里是从别的地方复制过来的，建议自己写的文档都统一一套风格，在这里提供了预测库下载，在Linux的编译文档上又没提供？

2021-04-28 07:15 UTC, jiangjiajun commented on deploy/cpp/docs/compile/paddle/windows.md
> +**在加载模型前，请检查你的模型是部署格式, 应该包括模型、参数、配置三个文件.比如是`__model__`、`__params__`、`infer_cfg.yml` 也可以是`model.pdmodel`、`model.pdiparams`、`deploy.yaml` 三个文件。如若不满足这个条件，请参考[部署模型导出](../../export_model.md)将模型导出为部署格式。**
这里不建议写得这么死板，没有要求模型命名一定是这样，例如seg就不是这样，另外部署模型导出的这个export_model.md是准备写什么的？

2021-04-28 09:04 UTC, heliqi commented on deploy/cpp/docs/compile/paddle/linux.md
> +| thread_num      | MKL推理的线程数，默认为1                                     | 默认为 1           |
写错注释了， 是openmp对batch加速的线程数

2021-04-28 09:06 UTC, heliqi commented on deploy/cpp/docs/compile/paddle/windows.md
> +**说明**：其中`C++`预测代码在`PaddleX\deploy\cpp` 目录，该目录不依赖任何`PaddleX`下其他目录。所有的公共实现代码在`model_deploy`目录下，而示例demo代码为`demo/model_infer.cpp`。
linux文档在新的代码分支下已经存在一部分，然后我是接着你的写。没注意已有内容的不一样

2021-04-28 09:51 UTC, merged

2021-05-22 00:57 UTC, chccc5 commented
win10 cmake 编译时发现推理库2.0+推理库名字修改，Cmake文件需要怎么修改 ？ 
修改如下，发现修改完报错
![image](https://user-images.githubusercontent.com/68001817/119209856-af80f380-badb-11eb-8788-cb4bce221860.png)

![image](https://user-images.githubusercontent.com/68001817/119209813-734d9300-badb-11eb-8ea3-c9c25a0c7ab9.png)