add TensorRT doc
PaddlePaddle/PaddleX pull request #764
Opened 2021-05-20 07:18 UTC by heliqi

1. 增加TensorRT部署使用文档
2. 修改部署ReadMe

2021-05-20 09:12 UTC, jiangjiajun requested changes

2021-05-20 09:12 UTC, jiangjiajun commented on deploy/cpp/docs/compile/tensorrt/trt.md
> +|            |                                                              |
后面空着一行

2021-05-20 09:12 UTC, jiangjiajun commented on deploy/cpp/docs/compile/tensorrt/trt.md
> +本文档将介绍如何基于Docker快速使用TensorRT部署Paddle转换的ONNX模型。 并以ResNet50模型为例， 讲述整个流程。[点击下载模型](https://bj.bcebos.com/paddlex/deploy2/models/resnet50_trt.tar.gz)
中文标点后无需加空格

2021-05-20 09:12 UTC, jiangjiajun commented on deploy/cpp/docs/compile/tensorrt/trt.md
> +例如[PaddleDetection模型部署指南](../../models/paddledetection.md) 中导出的DeepLabv3p模型，转换为onnx后是形状为[-1, 3,  -1, -1]的动态输入。修改配置文件如下，可将输入固化成[1, 3, 1024, 2048]形状:
PaddleDetection的DeepLabv3p模型？

2021-05-21 03:08 UTC, heliqi commented on deploy/cpp/docs/compile/tensorrt/trt.md
> +例如[PaddleDetection模型部署指南](../../models/paddledetection.md) 中导出的DeepLabv3p模型，转换为onnx后是形状为[-1, 3,  -1, -1]的动态输入。修改配置文件如下，可将输入固化成[1, 3, 1024, 2048]形状:
已改成seg

2021-05-21 03:33 UTC, jiangjiajun commented on deploy/cpp/docs/compile/tensorrt/trt.md
> +例如[PaddleSeg模型部署指南](../../models/paddleseg.md) 中导出的DeepLabv3p模型，转换为onnx后是形状为[-1, 3,  -1, -1]的动态输入。修改配置文件如下，可将输入固化成[1, 3, 1024, 2048]形状:
3和-1之前有两个空格

2021-05-21 07:45 UTC, merged