add OpenVINO engine
PaddlePaddle/PaddleX pull request #998
Opened 2021-07-29 04:33 UTC by heliqi

1. 由于detection模型用openvino转换有问题，只测试了 seg 和 clas
2. seg套件中的hardnet模型在openvino中结果有diff， 应该是模型转换有问题

如提交的为部署C++代码，请确认以下自测点是否完成（完成勾选即可），并保留以下的自测点列表，便于Reviewer知晓。

- [ ] Linux下测试通过
- - [ ] batch = 1 预测
- - [ ] batch > 1预测
- - [ ] 多GPU卡预测
- - [ ] TensorRT预测
- - [ ] Triton预测
- [ ] Windows下测试通过
- - [ ] batch = 1预测
- - [ ] batch > 1预测

2021-08-02 06:26 UTC, jiangjiajun requested changes

2021-08-02 06:26 UTC, jiangjiajun commented on deploy/cpp/model_deploy/engine/src/openvino_engine.cpp
> +    output->dtype = 0;
这里output->dtype没有枚举类型？

2021-08-02 06:26 UTC, jiangjiajun commented on deploy/cpp/model_deploy/ppseg/src/seg_postprocess.cpp
> +  } else if (output.dtype == INT32) {  // int32
这里又用了枚举类型

2021-08-02 12:35 UTC, heliqi commented on deploy/cpp/model_deploy/engine/src/openvino_engine.cpp
> +    output->dtype = 0;
已经改为枚举

2021-08-03 02:01 UTC, jiangjiajun approved these changes

2021-08-03 02:01 UTC, merged